version: '3.8'

services:
  web:
    build: ./python_app
    ports:
      - "8077:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg://kubsu:kubsu@db:5432/kubsu

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
      POSTGRES_DB: kubsu
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
