name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
          POSTGRES_DB: kubsu
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"

      - name: Run tests with pytest
        env:
          DATABASE_URL: postgresql+psycopg://kubsu:kubsu@localhost:5432/kubsu
        run: |
          pytest tests/ -v

  deploy:
    name: Build and Push Docker Image
    needs: test  # Зависит от успешного прохождения тестов
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Только при пуше в main

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./python_app
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/kubsu-app:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/kubsu-app:${{ github.sha }}